# Generated by Django 2.0.6 on 2018-09-28 14:30

from django.db import migrations, models
import django.db.models.deletion
import vserver.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(default=None, max_length=100)),
                ('hostname', models.CharField(default='localhost', max_length=100, verbose_name='Hostname')),
                ('owner', models.CharField(default='None', max_length=50, verbose_name='Owner/User/Admin')),
                ('os', models.CharField(default='None', max_length=50, verbose_name='Operating system')),
                ('decomissioned', models.BooleanField(default=False, verbose_name='Decomissioned')),
                ('decomissioned_date', models.DateField(default='2023-12-31')),
                ('server_cpu', models.CharField(max_length=100, verbose_name='Server CPU')),
                ('server_ram', models.CharField(max_length=100, verbose_name='Server RAM')),
                ('local_storage', models.CharField(max_length=100, verbose_name='Local storage')),
                ('current_roles', models.CharField(max_length=100, verbose_name='Current roles')),
                ('ip_v4_address', models.CharField(default='IPv4', max_length=100, verbose_name='IPv4 address')),
                ('ip_v4_address_public', models.CharField(default=None, max_length=100, verbose_name='Public ipv4 address')),
                ('ip_v6_address', models.CharField(default='IPv6', max_length=100, verbose_name='IPv6 address')),
                ('file_other', models.FileField(blank=True, default=None, upload_to=vserver.models.save_directory_path, verbose_name='Other files/Zip file if many')),
                ('other', models.TextField(max_length=500, verbose_name='Notes')),
                ('hypervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Server')),
            ],
            options={
                'verbose_name_plural': 'vServers',
            },
        ),
    ]
